### ISSUE TITLE
[dataset] Other datasets

### ISSUE THREAD

**Issue by Chenfeng1271** [luogen1996/RepAdapter#1]
Hi, thank you for your work. I notice these are only vtab-1k provided, can you provide other datasets for reproduction?

**Comment by IemProg** [comment]
Hi,

Wonderful, work. Thanks for sharing the code.

Could you please share with us, the code for video classification and semantic segmentation for reproduction ?

**Comment by luogen1996** [comment]
> Hi,
> 
> Wonderful, work. Thanks for sharing the code.
> 
> Could you please share with us, the code for video classification and semantic segmentation for reproduction ?

Our code of video classification follows the [AdaptFormer](https://github.com/ShoufaChen/AdaptFormer). You can insert RepAdapter before the MHSA and FFN, and then reproduce our results.  For semantic segmentation, we use [SETR](https://github.com/fudan-zvg/SETR) and insert RepAdapter into the visual backbone.
