### ISSUE TITLE
[dataset] file integrity of vtab-1k

### ISSUE THREAD

**Issue by Chenfeng1271** [luogen1996/RepAdapter#2]
Hi, thank you for your excellent work. I want to reproduce the performance, but the downloaded vtab1k dataset from the [link](https://onedrive.live.com/?cid=4635947f2653c56a&id=4635947F2653C56A%211403&authkey=%21APzLncdff%2Dsuumo) is somewhat wrong, resulting in extraction fail. I try it on two computers, but it shows the same result. Can you provide a new link for download? Thank you.

**Comment by luogen1996** [comment]
To download the dataset, you may need to use VPN.  We upload the dataset to Baidu Cloud：
link：https://pan.baidu.com/s/1MSerX0jEqfwfYNpnvGGVxA 
verification code：1tdl

**Comment by ShuvenduRoy** [comment]
Could you please share this in google drive or onedrive? I can't access Baidu. The link that you have fails to extract after download.

**Comment by RaptorMai** [comment]
I also experienced the same extraction issue. It would be really appreciated if you could share the data on google drive or onedrive.

**Comment by luogen1996** [comment]
> I also experienced the same extraction issue. It would be really appreciated if you could share the data on google drive or onedrive.

We have uploaded the dataset to google drive, here is the [download link](https://drive.google.com/file/d/1tfflwfG5H0RWzjwBMlmcAa4FsxeG3d51/view?usp=share_link).

**Comment by DavidYanAnDe** [comment]
the download link only contain 12 datasets, but I believe that there should be 19 datasets in VTAB-1k, could you please provide the complete datasets?

**Comment by luogen1996** [comment]
> the download link only contain 12 datasets, but I believe that there should be 19 datasets in VTAB-1k, could you please provide the complete datasets?

Sorry for this mistake, we have uploaded the full datasets on [google drive](https://drive.google.com/file/d/1yZKwiKdsBzTfBgnStRveYMokc7GMMd5p/view?usp=share_link). The download link is already updated.

**Comment by DavidYanAnDe** [comment]
> > the download link only contain 12 datasets, but I believe that there should be 19 datasets in VTAB-1k, could you please provide the complete datasets?
> 
> Sorry for this mistake, we have uploaded the full datasets on [google drive](https://drive.google.com/file/d/1yZKwiKdsBzTfBgnStRveYMokc7GMMd5p/view?usp=share_link). The download link is already updated.

thank you very much, wish you every succees :)
